# Generated by Django 3.2.13 on 2023-03-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_followupcard_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupcard',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Closed'), (3, 'Paid')], default=1),
        ),
        migrations.AlterField(
            model_name='followupcard',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
